[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 5
headless = true
port = 8501

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
